ALTER TABLE orders ADD COLUMN recipient_name VARCHAR(100) NULL;
ALTER TABLE orders ADD COLUMN phone VARCHAR(30) NULL;
ALTER TABLE orders ADD COLUMN zip_code VARCHAR(10) NULL;
ALTER TABLE orders ADD COLUMN address VARCHAR(500) NULL;
ALTER TABLE orders ADD COLUMN payment_method VARCHAR(30) NULL;
ALTER TABLE orders ADD COLUMN note VARCHAR(500) NULL;
